# Build stage
FROM node:14 as build

WORKDIR /app

# Copier le package.json et le package-lock.json
COPY client/package*.json ./

RUN npm install

# Copier tous les autres fichiers
COPY client/ ./

# Build l'application React
RUN npm run build

# Production stage
FROM nginx:alpine

# Copier les fichiers construits depuis le build précédent
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
